import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Plus, 
  Search, 
  Filter, 
  MoreHorizontal,
  Phone,
  Mail,
  FileText,
  CheckCircle,
  Briefcase,
  Users,
  Loader2
} from 'lucide-react';
import { Header } from '@/components/layout/Header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { cn, formatCurrency } from '@/lib/utils';
import { toast } from 'sonner';
import { useClientsConseil, useCreateClientConseil, ClientConseilDB } from '@/hooks/useConseil';
import { useAuth } from '@/contexts/AuthContext';

type StatutClientConseil = 'ACTIF' | 'SUSPENDU' | 'RESILIE';

const getStatutBadge = (statut: StatutClientConseil) => {
  switch (statut) {
    case 'ACTIF':
      return <Badge className="bg-success/10 text-success border-success/20">Actif</Badge>;
    case 'SUSPENDU':
      return <Badge className="bg-warning/10 text-warning border-warning/20">Suspendu</Badge>;
    case 'RESILIE':
      return <Badge className="bg-destructive/10 text-destructive border-destructive/20">Résilié</Badge>;
  }
};

export default function ClientsPage() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { data: clients = [], isLoading } = useClientsConseil();
  const createClient = useCreateClientConseil();
  
  const [searchTerm, setSearchTerm] = useState('');
  const [isNewClientDialogOpen, setIsNewClientDialogOpen] = useState(false);
  const [newClient, setNewClient] = useState({
    nom: '',
    type: 'morale' as 'physique' | 'morale',
    telephone: '',
    email: '',
    adresse: '',
    honoraireMensuel: 0,
    jourFacturation: 1,
    notes: ''
  });

  const filteredClients = clients.filter(client =>
    client.nom.toLowerCase().includes(searchTerm.toLowerCase()) ||
    client.reference.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const activeClients = clients.filter(c => c.statut === 'ACTIF');
  const totalHonoraires = activeClients.reduce((sum, c) => sum + c.honoraire_mensuel, 0);

  const handleCreateClient = async () => {
    if (!newClient.nom || !newClient.honoraireMensuel) {
      toast.error('Veuillez remplir les champs obligatoires');
      return;
    }
    
    try {
      await createClient.mutateAsync({
        reference: '', // Will be generated by trigger
        nom: newClient.nom,
        type: newClient.type,
        telephone: newClient.telephone || null,
        email: newClient.email || null,
        adresse: newClient.adresse || null,
        honoraire_mensuel: newClient.honoraireMensuel,
        jour_facturation: newClient.jourFacturation,
        statut: 'ACTIF',
        notes: newClient.notes || null,
        created_by: user?.id || ''
      });
      
      setIsNewClientDialogOpen(false);
      setNewClient({
        nom: '',
        type: 'morale',
        telephone: '',
        email: '',
        adresse: '',
        honoraireMensuel: 0,
        jourFacturation: 1,
        notes: ''
      });
    } catch (error) {
      // Error handled in hook
    }
  };

  const handleRowClick = (clientId: string) => {
    navigate(`/conseil/clients/${clientId}`);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <Header 
        title="Clients Conseils" 
        subtitle="Gestion des abonnements et assistance juridique"
        actions={
          <Button className="gap-2" onClick={() => setIsNewClientDialogOpen(true)}>
            <Plus className="h-4 w-4" />
            Nouveau client
          </Button>
        }
      />

      <div className="p-6 space-y-6 animate-fade-in">
        {/* Stats rapides */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-card border rounded-lg p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Users className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{activeClients.length}</p>
                <p className="text-sm text-muted-foreground">Clients actifs</p>
              </div>
            </div>
          </div>
          <div className="bg-card border rounded-lg p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-success/10">
                <Briefcase className="h-5 w-5 text-success" />
              </div>
              <div>
                <p className="text-2xl font-bold">{formatCurrency(totalHonoraires)}</p>
                <p className="text-sm text-muted-foreground">Honoraires mensuels</p>
              </div>
            </div>
          </div>
        </div>

        {/* Filtres et recherche */}
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Rechercher un client..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          <Button variant="outline" className="gap-2">
            <Filter className="h-4 w-4" />
            Filtres
          </Button>
        </div>

        {/* Tableau des clients */}
        <div className="bg-card rounded-lg border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Référence</TableHead>
                <TableHead>Client</TableHead>
                <TableHead>Contact</TableHead>
                <TableHead className="text-right">Honoraires/mois</TableHead>
                <TableHead>Facturation</TableHead>
                <TableHead>Statut</TableHead>
                <TableHead className="w-12"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredClients.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                    Aucun client trouvé
                  </TableCell>
                </TableRow>
              ) : (
                filteredClients.map((client) => (
                  <TableRow 
                    key={client.id} 
                    className="cursor-pointer hover:bg-muted/50"
                    onClick={() => handleRowClick(client.id)}
                  >
                    <TableCell className="font-mono text-sm">{client.reference}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-3">
                        <div className={cn(
                          "w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium",
                          client.type === 'morale' ? 'bg-primary/10 text-primary' : 'bg-info/10 text-info'
                        )}>
                          {client.nom.split(' ').map(n => n[0]).join('').slice(0, 2)}
                        </div>
                        <div>
                          <p className="font-medium">{client.nom}</p>
                          <p className="text-xs text-muted-foreground">
                            {client.type === 'morale' ? 'Personne morale' : 'Personne physique'}
                          </p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="space-y-1">
                        {client.telephone && (
                          <div className="flex items-center gap-1 text-sm">
                            <Phone className="h-3 w-3 text-muted-foreground" />
                            {client.telephone}
                          </div>
                        )}
                        {client.email && (
                          <div className="flex items-center gap-1 text-sm text-muted-foreground">
                            <Mail className="h-3 w-3" />
                            {client.email}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right font-medium">
                      {formatCurrency(client.honoraire_mensuel)}
                    </TableCell>
                    <TableCell>
                      <span className="text-sm text-muted-foreground">
                        Le {client.jour_facturation} du mois
                      </span>
                    </TableCell>
                    <TableCell>{getStatutBadge(client.statut as StatutClientConseil)}</TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}>
                          <Button variant="ghost" size="icon">
                            <MoreHorizontal className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); navigate(`/conseil/clients/${client.id}`); }}>
                            <FileText className="h-4 w-4 mr-2" />
                            Voir détails
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); toast.success('Facture générée'); }}>
                            <FileText className="h-4 w-4 mr-2" />
                            Générer facture
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Dialog nouveau client */}
      <Dialog open={isNewClientDialogOpen} onOpenChange={setIsNewClientDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Nouveau client conseil</DialogTitle>
            <DialogDescription>
              Ajouter un nouveau client avec abonnement mensuel
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="type">Type de client *</Label>
              <Select
                value={newClient.type}
                onValueChange={(value: 'physique' | 'morale') => setNewClient({ ...newClient, type: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="morale">Personne morale (Société)</SelectItem>
                  <SelectItem value="physique">Personne physique</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="nom">Nom / Raison sociale *</Label>
              <Input
                id="nom"
                value={newClient.nom}
                onChange={(e) => setNewClient({ ...newClient, nom: e.target.value })}
                placeholder="Ex: Société Alpha Industries"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="telephone">Téléphone</Label>
                <Input
                  id="telephone"
                  value={newClient.telephone}
                  onChange={(e) => setNewClient({ ...newClient, telephone: e.target.value })}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  value={newClient.email}
                  onChange={(e) => setNewClient({ ...newClient, email: e.target.value })}
                />
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="adresse">Adresse</Label>
              <Input
                id="adresse"
                value={newClient.adresse}
                onChange={(e) => setNewClient({ ...newClient, adresse: e.target.value })}
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="honoraires">Honoraires mensuels (FCFA) *</Label>
                <Input
                  id="honoraires"
                  type="number"
                  value={newClient.honoraireMensuel || ''}
                  onChange={(e) => setNewClient({ ...newClient, honoraireMensuel: parseInt(e.target.value) || 0 })}
                  placeholder="750000"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="jourFacturation">Jour de facturation</Label>
                <Select
                  value={newClient.jourFacturation.toString()}
                  onValueChange={(value) => setNewClient({ ...newClient, jourFacturation: parseInt(value) })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {[1, 5, 10, 15, 20, 25].map((jour) => (
                      <SelectItem key={jour} value={jour.toString()}>
                        Le {jour} du mois
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                value={newClient.notes}
                onChange={(e) => setNewClient({ ...newClient, notes: e.target.value })}
                placeholder="Informations complémentaires..."
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsNewClientDialogOpen(false)}>
              Annuler
            </Button>
            <Button onClick={handleCreateClient} disabled={createClient.isPending}>
              {createClient.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              <CheckCircle className="h-4 w-4 mr-2" />
              Créer le client
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
